spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

storage:
  upload-dir: uploads/
  allowed-file-types: image/jpeg,image/png,image/gif



# Configurazione Swagger-UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs


jwt:
  secret-key: "8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb"

logging:
  level:
    org:
      springframework.security: DEBUG
    it:
      microssi.ecofish.security: DEBUG
